---
title: "Untitled"
output: html_document
---

```{r}
ref <- Refs$inv7p11.2
data("SNPsR2")
R2s <- SNPsR2$inv7p11.2
data("hetRefs")
hRefs <- hetRefs$inv7p11.2

library(BiocParallel)
new_michigan_inv <- scoreInvHap(SNPlist = new_michigan, SNPsR2 = R2s, hetRefs = hRefs, Refs = ref, imputed = TRUE, verbose = TRUE, BPPARAM = MulticoreParam(10))
# 15-20 nucleos
michigan_inv

new_minimac_inv <- scoreInvHap(SNPlist = new_minimac, SNPsR2 = R2s, hetRefs = hRefs, Refs = ref, imputed = TRUE, verbose = TRUE, BPPARAM = MulticoreParam(10))
minimac_inv

scoreinvhap_table <- table(Michigan = classification(new_michigan_inv)[sort(names(classification(new_michigan_inv)))], 
      Minimac = classification(new_minimac_inv)[sort(names(classification(new_minimac_inv)))])

scoreinvhap_table
sum(diag(scoreinvhap_table))/sum(scoreinvhap_table)

#classification(minimac_inv)[sort(names(classification(minimac_inv)))]

source("InversionNGSutils.R")

new_michigan_invclust <- computeInvClust(range = GRanges(c(r="7:54290974-54386821")), vcffile = "/scratch/itolosana/impute/new_michigan_imputation/final_michigan_chr7.vcf.gz")
plotInv(new_michigan_invclust, classification = classification(new_michigan_inv))

new_minimac_invclust <- computeInvClust(range = GRanges(c(r="7:54290974-54386821")), vcffile = "/scratch/itolosana/impute/new_minimac_imputation/final_minimac_chr7.vcf.gz")
plotInv(minimac_invclust, classification = classification(minimac_inv))



hist(cor_by_ind, breaks=seq(0, 1, by=0.02), main="SNPsR2$inv7p11.2", xlab="R2")

hist(SNPsR2$inv7p11.2[rownames(new_michigan)], breaks=seq(0, 1, by=0.02), main="SNPsR2$inv7p11.2[rownames(new_michigan)]", xlab="R2")
hist(SNPsR2$inv7p11.2, breaks=seq(0, 1, by=0.02), main="SNPsR2$inv7p11.2", xlab="R2")
```




```{r}
library(VariantAnnotation)

nofilter_minimac_7 <- readVcf("/scratch/itolosana/impute/new_minimac_imputation/nofilter_invreg_minimac_chr7.vcf.gz", "hg19")
nofilter_minimac_8 <- readVcf("/scratch/itolosana/impute/new_minimac_imputation/nofilter_invreg_minimac_chr8.vcf.gz", "hg19")
nofilter_minimac_17 <- readVcf("/scratch/itolosana/impute/new_minimac_imputation/nofilter_invreg_minimac_chr17.vcf.gz", "hg19")


nofilter_michigan_7 <- readVcf("/scratch/itolosana/impute/new_michigan_imputation/nofilter_invreg_michigan_chr7.vcf.gz", "hg19")
nofilter_michigan_8 <- readVcf("/scratch/itolosana/impute/new_michigan_imputation/nofilter_invreg_michigan_chr8.vcf.gz", "hg19")
nofilter_michigan_17 <- readVcf("/scratch/itolosana/impute/new_michigan_imputation/nofilter_invreg_michigan_chr17.vcf.gz", "hg19")


nofilter_minimac_17[,sort(rownames(nofilter_minimac_17))]

head(info(nofilter_minimac_17)$R2)

library(scoreInvHap)
data("SNPsR2")
names(SNPsR2)

SNPsR2$inv7p11.2
SNPsR2$inv8p23.1
SNPsR2$inv17q21.31

snps_minimac_7 <- intersect(rownames(info(nofilter_minimac_7)), names(SNPsR2$inv7p11.2))

# Imputation R2 vs scoreInvHap R2 (chr7)
ggplot() +
  geom_point(aes(x = info(nofilter_minimac_7)[snps_minimac_7,]$R2, 
                 y = SNPsR2$inv7p11.2[snps_minimac_7])) + 
                #alpha = 0.5) +
  geom_vline(aes(xintercept=0.5), colour="red") +
  ggtitle("Minimac chr 7") +
  xlab("Imputation R2") +
  ylab("scoreInvHap R2")

# Histogram scoreInvHap R2 with the imputation data NO filtered (chr7)
ggplot() +
  geom_histogram(aes(SNPsR2$inv7p11.2[snps_minimac_7]), binwidth = 0.02) +
  ggtitle("No filtered chr7") +
  xlab("scoreInvHapR2")


snps_filt_minimac_7 <- intersect(rownames(info(minimac_chr7)), names(SNPsR2$inv7p11.2))

# Histogram scoreInvHap R2 with the imputation data filtered (chr7)
ggplot() +
  geom_histogram(aes(SNPsR2$inv7p11.2[snps_filt_minimac_7]), binwidth = 0.02) +
  ggtitle("Filtered chr7") +
  xlab("scoreInvHapR2")

par(mfrow=c(1,2))
hist(SNPsR2$inv7p11.2[rownames(minimac_chr7)], breaks=seq(0, 1, by=0.02), main="Filtered chr7", xlab="scoreInvHapR2")
hist(SNPsR2$inv7p11.2[rownames(nofilter_minimac_7)], breaks=seq(0, 1, by=0.02), main="No filtered chr7", xlab="scoreInvHapR2")


cor(info(nofilter_minimac_7)[snps_minimac_7,]$R2, SNPsR2$inv7p11.2[snps_minimac_7])


library(scoreInvHap)
data("Refs")
# Check which is the inversion we are comparing
ref <- Refs$inv7p11.2
data("SNPsR2")
R2s <- SNPsR2$inv7p11.2
data("hetRefs")
hRefs <- hetRefs$inv7p11.2

library(BiocParallel)

nofilter_minimac_inv_7 <- scoreInvHap(SNPlist = nofilter_minimac_7, SNPsR2 = R2s, hetRefs = hRefs, Refs = ref, imputed = TRUE, verbose = TRUE, BPPARAM = MulticoreParam(10))

nofilter_michigan_inv_7 <- scoreInvHap(SNPlist = nofilter_michigan_7, SNPsR2 = R2s, hetRefs = hRefs, Refs = ref, imputed = TRUE, verbose = TRUE, BPPARAM = MulticoreParam(10))


source("InversionNGSutils.R")

nofilter_minimac_invclust_7 <- computeInvClust(range = GRanges(c(r="7:54290974-54386821")), vcffile = "/scratch/itolosana/impute/new_minimac_imputation/nofilter_invreg_minimac_chr7.vcf.gz")
plotInv(minimac_invclust, classification = classification(minimac_inv))



```

